### PR TITLE
Still there is a problem between connection.

### PR DESCRIPTION
**Pull request by tony-sanguk**
Using thread, I did test the connection between an agent and dummy.
Add two Class named AgentThread and DummyThread in `utils/multithread.py` to manage them. Each thread has an agent or a dummy. When the thread starts, an agent or a dummy starts to act their work, such as probe agent act to achieve its goal.

With threads, I success the two threads which are one for probe agent, and one for our dummy. Nevertheless, still there was a problem, so I did delete `flags=zmq.NOBLOCK` in `communicator.py`. Then, the dummy can get first msg, but it fell into a deadlock. I think it was occurred because of synchronization. So, Can Anybody help me to figure out this problem?

### CODE REVIEW

**Comment by gemblerz** [comment]
I will take a look at that and try to help you.

**Comment by tony-sanguk** [comment]
I used `dummy.py` to test connection!

**Comment by tony-sanguk** [comment]
- Figured out the connection problem by using **zmq.PAIR** option to open socket.
- **zmq.PAIR** accepts one-to-many connection.
- I tested to send and receive msg between an agent and one dummy, use `dummy.py` to test.
- I think this is also meet our thought, it seems like human conversation, the agents always listen and if they hear something, just can record msg to knowledge base.

**Comment by tony-sanguk** [comment]
Now, still there are a small problem, it is working well.
After check it, please merge it. Use `dummy.py`, I used two agents and one dummy to test connection.

- Sometimes, the first message disappeared after connecting from PUB to SUB socket.
- It could be figured out by programming that is sending empty msg when the initial connection is succeed.

**Pull request merged**
